# Generated by Django 4.1.2 on 2022-11-07 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("student_management_app", "0006_alter_customuser_first_name_students1"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                choices=[(1, "HOD"), (2, "Staff"), (3, "Student"), (4, "Student1")],
                default=1,
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="FeedBackStaffs_pic",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("feedback", models.TextField()),
                ("feedback_pic", models.FileField(upload_to="")),
                ("feedback_reply", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "staff_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="student_management_app.staffs",
                    ),
                ),
            ],
        ),
    ]
